<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="urn:3GPP:metadata:2025:MBMS:FLUTE:FDT"
	xmlns="urn:3GPP:metadata:2025:MBMS:FLUTE:FDT" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	elementFormDefault="qualified">
	<xs:annotation>
		<xs:documentation>MBMS FLUTE FDT schema extensions (Release 19)</xs:documentation>
		<xs:documentation>3GPP TS 26.346 clause 7.2.10.2</xs:documentation>
		<xs:documentation>Copyright © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.</xs:documentation>
	</xs:annotation>

	<xs:attribute name="Repair-Start" type="xs:dateTime"/>
	<xs:attribute name="Repair-Limit-Percentage" type="xs:unsignedInt"/>
</xs:schema>
