<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="urn:3gpp:metadata:2013:MBMS:scheduleDescription"
	xmlns="urn:3gpp:metadata:2013:MBMS:scheduleDescription"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	<xs:annotation>
		<xs:documentation>MBMS Schedule Description schema extensions (Release 12)</xs:documentation>
		<xs:documentation>3GPP TS 26.346 clause 11.2A.2.3</xs:documentation>
		<xs:documentation>Copyright © 2013, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.</xs:documentation>
	</xs:annotation>

	<xs:attribute name="unicastOnly" type="xs:boolean" default="false"/>

	<xs:element name="FDTInstanceURI" type="xs:anyURI"/>

	<xs:element name="recurrenceAndMonitoring" type="recurrenceAndMonitoringType"/>
	<xs:complexType name="recurrenceAndMonitoringType">
		<xs:sequence>
			<xs:element name="interval" type="xs:duration"/>
			<xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="mode" type="xs:boolean"/>
		<xs:anyAttribute processContents="skip"/>
	</xs:complexType>

	<xs:attribute name="sessionDescriptionURI" type="xs:anyURI"/>
</xs:schema>
