<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="urn:3GPP:metadata:2005:MBMS:mskRequest"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns="urn:3GPP:metadata:2005:MBMS:mskRequest"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:annotation>
		<xs:documentation>MBMS Service Protection MSK request schema</xs:documentation>
		<xs:documentation>3GPP TS 26.346 clause 11.6.1</xs:documentation>
		<xs:documentation>Copyright © 2005, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.</xs:documentation>
	</xs:annotation>

	<xs:element name="mbmsMSKRequest">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MSK" type="MSKType" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:anyAttribute processContents="skip"/>
		</xs:complexType>
		</xs:element>

	<xs:complexType name="MSKType">
		<xs:sequence>
			<xs:element name="keyDomainID" type="xs:base64Binary" minOccurs="1" maxOccurs="1"/>
			<xs:element name="MSKID" type="MSKIDType" minOccurs="1" maxOccurs="1"/>	
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="MSKIDType">
		<xs:restriction base="xs:base64Binary">
			<xs:length value="4"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>
