<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="urn:3gpp:metadata:2005:MBMS:associatedProcedure-rel-14-extension"
	xmlns="urn:3gpp:metadata:2005:MBMS:associatedProcedure-rel-14-extension"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	<xs:annotation>
		<xs:documentation>MBMS Associated Delivery Procedures Description schema extensions (Release 14)</xs:documentation>
		<xs:documentation>3GPP TS 26.346 clause 9.5.1</xs:documentation>
		<xs:documentation>Copyright © 2016, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.</xs:documentation>
	</xs:annotation>

	<xs:attribute name="reportInterval" type="xs:duration"/>
</xs:schema>
