<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="urn:3GPP:metadata:2017:MBMS:userServiceDescription" version="2"
	xmlns="urn:3GPP:metadata:2017:MBMS:userServiceDescription"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	<xs:annotation>
		<xs:documentation>MBMS User Service Bundle Description schema extensions (Release 14)</xs:documentation>
		<xs:documentation>3GPP TS 26.346 clause 11.2.1.2</xs:documentation>
		<xs:documentation>Copyright © 2017, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.</xs:documentation>
	</xs:annotation>

	<xs:attribute name="romService" type="xs:boolean" default="false"/>
</xs:schema>
