openapi: 3.0.1
info:
  title: Scenario specific Intent Expectations - 5GCNetworkExpectation
  version: 20.0.0
  description: >-
    OAS 3.0.1 definition of scenario specific Intent Expectations - 5GCNetworkExpectation
    © 2026, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.
externalDocs:
  description: 3GPP TS 28.312; Intent driven management services for mobile networks
  url: http://www.3gpp.org/ftp/Specs/archive/28_series/28.312/
paths: {}
components:
  schemas:

    #-------Definition of the Scenario specific IntentExpectation dataType ----------#  
    5GCNetworkExpectation:
      description: >-
        This data type is the "IntentExpectation" data type with specialisations to represent MnS consumer's expectations for 5GC network delivering   
      type: object
      properties:
        expectationId:
          type: string
        expectationVerb:
           $ref: 'TS28312_IntentNrm.yaml#/components/schemas/ExpectationVerb'
        expectationObject:
           $ref: '#/components/schemas/5GCNetworkExpectationObject'
        expectationTargets:
          type: array
          uniqueItems: true
          items:
            type: object
            oneOf:
              - $ref: '#/components/schemas/MaxNumberofPDUsessionsTarget'
              - $ref: '#/components/schemas/MaxNumberofRegisteredsubscribersTarget'
              - $ref: '#/components/schemas/IncomingDataTarget'
              - $ref: '#/components/schemas/OutgoingDataTarget'
              - $ref: '#/components/schemas/LatencyTarget'              
              - $ref: 'TS28312_IntentNrm.yaml#/components/schemas/ExpectationTarget'
        expectationContexts:
          type: array
          uniqueItems: true
          items:
            type: object
            oneOf:
              - $ref: '#/components/schemas/StartTimeContext'
              - $ref: '#/components/schemas/ResourceSharingLevelContext'
              - $ref: 'TS28312_IntentNrm.yaml#/components/schemas/DecompositionAssistingContext'              
              - $ref: 'TS28312_IntentNrm.yaml#/components/schemas/Context'
      required:
        - expectationId
    #-------Definition of the Scenario specific IntentExpectation dataType ----------#

   #-------Definition of the scenario specific ExpectationObject dataType ----------#
    5GCNetworkExpectationObject:
      description: >-
        This data type is the "ExpectationObject" data type with specialisations for 5GCNetworkExpectation
      type: object
      properties:
        objectType:
          type: string
          enum:
            - 5GC_SUBNETWORK #value for 5GC Network Expectation--#
        objectInstance:
          $ref: "TS28623_ComDefs.yaml#/components/schemas/Dn"
        objectContexts:
          type: array
          uniqueItems: true
          items:
            type: object
            oneOf:
              - $ref: '#/components/schemas/NfTypeContext'
              - $ref: '#/components/schemas/NfInstanceLocationContext'
              - $ref: 'TS28312_RadioNetworkExpectation.yaml#/components/schemas/PLMNContext'
              - $ref: '#/components/schemas/TaiContext'
              - $ref: '#/components/schemas/ServingScopeContext'
              - $ref: '#/components/schemas/DnnContext'
              - $ref: '#/components/schemas/PreferredUPFContext'              
              - $ref: 'TS28312_IntentNrm.yaml#/components/schemas/Context'
   #-------Definition of the scenario specific ExpectationObject dataType ----------#     

  #-------Definition of the Scenario specific ExpectationTarget dataType----------#      
    MaxNumberofPDUsessionsTarget:
      description: >-
        This data type is the "ExpectationTarget" data type with specialisations for MaxNumberofPDUsessionsTarget.It describes the maximum number of PDU sessions for 5GC
        SubNetwork supporting that the intent expectation is applied. For details, see maxNumberofPDUsessions in clause 5.3.1.2 in TS 28.552 [12].     
      type: object
      properties:
        targetName:
          type: string
          enum:
            - MaxNumberofPDUsessions
        targetCondition:
          type: string
          enum:
            - IS_LESS_THAN
        targetValueRange:
          type: integer
        targetContexts:
          $ref: '#/components/schemas/5GSessionContext'
    5GSessionContext:
      description: >-
        This data type is the "TargetContext" data type with specialisations for 5GSessionContext.It describes the maximum supported 5G PDU session of the 5GC SubNetwork
        related to the intent expectation.
      type: object
      properties:
        contextAttribute:
          type: string
          enum:
            - 5GSession
        contextCondition:
          type: string
          enum:
            - IS_less_THAN
        contextValueRange:
          type: integer          
    MaxNumberofRegisteredsubscribersTarget:
      description: >-
        This data type is the "ExpectationTarget" data type with specialisations for MaxNumberofRegisteredsubscribersTarget.It describes the maximum number of Registered
        subscribers for 5GC SubNetwork supporting that the intent expectation is applied. For details, see maxNumberofRegisteredsubscribers in clause 5.6.2 in TS 28.552 [12].     
      type: object
      properties:
        targetName:
          type: string
          enum:
            - MaxNumberofRegisteredsubscribers
        targetCondition:
          type: string
          enum:
            - IS_LESS_THAN
        targetValueRange:
          type: integer
    IncomingDataTarget:
      description: >-
        This data type is the "ExpectationTarget" data type with specialisations for IncomingDataTarget.It describes the maximum incoming data packets for 5GC SubNetwork
        related to the intent expectation. For details, see N6 incoming link usage measurement in clause 5.4.2.1 in TS 28.552 [12].     
      type: object
      properties:
        targetName:
          type: string
          enum:
            - IncomingData
        targetCondition:
          type: string
          enum:
            - IS_LESS_THAN
        targetValueRange:
          type: integer
    OutgoingDataTarget:
      description: >-
        This data type is the "ExpectationTarget" data type with specialisations for OutgoingDataTarget.It describes the maximum outgoing data packets for 5GC SubNetwork
        related to the intent expectation. For details, see N6 outgoing link usage measurement in clause 5.4.2.2 in TS 28.552 [12].     
      type: object
      properties:
        targetName:
          type: string
          enum:
            - OutgoingData
        targetCondition:
          type: string
          enum:
            - IS_LESS_THAN
        targetValueRange:
          type: integer
    LatencyTarget:
      description: >-
        This data type is the "ExpectationTarget" data type with specialisations for LatencyTarget.
        It represents the latency target for the core network service (ending at the UPF) that the 
        intent expectation is applied.
      type: object
      properties:
        targetName:
          type: string
          enum:
            - Latency
        targetCondition:
          type: string
          enum:
            - IS_LESS_THAN
        targetValueRange:
          type: integer            
  #-------Definition of the Scenario specific ExpectationTarget dataType----------#  
  #-------Definition of the concrete ObjectContext dataType----------------#
    NfTypeContext:          
      description: >-
        This data type is the "ObjectContext" data type with specialisations for NfTypeContext
      type: object
      properties:
        contextAttribute:
          type: string
          enum:
            - NfType
        contextCondition:
          type: string
          enum:
            - IS_ALL_OF
        contextValueRange:
          type: array
          uniqueItems: true
          items:
            $ref: 'TS28541_5GcNrm.yaml#/components/schemas/NFType'
    NfInstanceLocationContext:
      description: >-
        This data type is the "ObjectContext" data type with specialisations for NfInstanceLocationContext 
      type: object
      properties:
        contextAttribute:
          type: string
          enum:
            - NfInstanceLocation
        contextCondition:
          type: string
          enum:
            - IS_ALL_OF
        contextValueRange:
          type: array
          uniqueItems: true
          items:
            type: string
    TaiContext: 
      description: >-
        This data type is the "ObjectContext" data type with specialisations for TaiContext
      type: object
      properties:
        contextAttribute:
          type: string
          enum:
            - Tai
        contextCondition:
          type: string
          enum:
            - IS_ALL_OF
        contextValueRange:
          type: array
          uniqueItems: true
          items:
            $ref: 'TS28623_GenericNrm.yaml#/components/schemas/Tai'
    ServingScopeContext:          
      description: >-
        This data type is the "ObjectContext" data type with specialisations for ServingScopeContext   
      type: object
      properties:
        contextAttribute:
          type: string
          enum:
            - ServingScope
        contextCondition:
          type: string
          enum:
            - IS_ALL_OF
        contextValueRange:
          type: array
          uniqueItems: true
          items:
            type: string
    DnnContext:
      description: >-
        This data type is the "ObjectContext" data type with specialisations for DnnContext   
      type: object
      properties:
        contextAttribute:
          type: string
          enum:
            - Dnn
        contextCondition:
          type: string
          enum:
            - IS_ALL_OF
        contextValueRange:
          type: array
          uniqueItems: true
          items:
            type: string
    PreferredUPFContext:
      description: >-
        This data type is the "ObjectContext" data type with specialisations for PreferredUPFContext   
      type: object
      properties:
        contextAttribute:
          type: string
          enum:
            - PreferredUPF
        contextCondition:
          type: string
          enum:
            - IS_ALL_OF
        contextValueRange:
          type: array
          uniqueItems: true
          items:
            type: string                
    #-------Definition of the concrete ObjectContext dataType----------------#

  #-------Definition of the concrete ExpectationContext dataType----------------#
    StartTimeContext:
      description: >-
        This data type is the "ExpectationContext" data type with specialisations for StartTimeContext       
      type: object
      properties:
        contextAttribute:
          type: string
          enum:
            - StartTime
        contextCondition:
          type: string
          enum:
            - IS_EQUAL_TO
        contextValueRange:
          $ref: 'TS28623_ComDefs.yaml#/components/schemas/DateTime'
    ResourceSharingLevelContext:
      description: >-
        This data type is the "ExpectationContext" data type with specialisations for ResourceSharingLevelContext          
      type: object
      properties:
        contextAttribute:
          type: string
          enum:
            - ResourceSharingLevel
        contextCondition:
          type: string
          enum:
            - IS_EQUAL_TO
        contextValueRange:
          $ref: "TS28541_SliceNrm.yaml#/components/schemas/SharingLevel"          
  #-------Definition of the concrete ExpectationContext dataType----------------# 
